---Question 1  Total number of enrollments by course category
SELECT 
    c.category,
    COUNT(e.enrollment_id) AS total_enrollments
FROM dbo.enrollments e
JOIN dbo.courses c ON e.course_id = c.course_id
GROUP BY c.category
ORDER BY total_enrollments DESC;


-- Question 2: Which courses have the highest and lowest completion rates?
SELECT 
    c.course_name,
    COUNT(e.enrollment_id) AS total_enrollments,
    SUM(CASE WHEN e.status = 'Completed' THEN 1 ELSE 0 END) AS completed_count,
    ROUND(
        (CAST(SUM(CASE WHEN e.status = 'Completed' THEN 1 ELSE 0 END) AS FLOAT) / 
         COUNT(e.enrollment_id)) * 100, 2
    ) AS completion_rate_pct
FROM 
    enrollments e
JOIN 
    courses c ON e.course_id = c.course_id
GROUP BY 
    c.course_name
ORDER BY 
    completion_rate_pct DESC;




---Question 3: Monthly Enrollment Trends
SELECT 
    FORMAT(enrollment_date, 'yyyy-MM') AS enrollment_month,
    COUNT(enrollment_id) AS total_enrollments
FROM enrollments
GROUP BY FORMAT(enrollment_date, 'yyyy-MM')
ORDER BY enrollment_month;


SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'courses';

---question 4: Revenue Generated by Course
SELECT 
    c.course_name,
    COUNT(e.enrollment_id) AS total_enrollments,
    c.price_usd,
    ROUND(COUNT(e.enrollment_id) * c.price_usd, 2) AS total_revenue_usd
FROM 
    enrollments e
JOIN 
    courses c ON e.course_id = c.course_id
GROUP BY 
    c.course_name, c.price_usd
ORDER BY 
    total_revenue_usd DESC;